postgres: &postgres
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: vagrant
  password: blocio

development:
  <<: *postgres
  database: blog_app_development

test:
  <<: *postgres
  database: blog_app_test

production:
  <<: *postgres
  database: blog_app_production
